### ISSUE TITLE
Use HttpOnly and Secure

### ISSUE THREAD

**Issue by klegul** [ypsilondev/Quizzy-Backend#5]
Because this cookie is only send via http api request and not read by JavaScript it is more secure to set HttpOnly attribut on this cookie. Using Secure will only send the cookie over https which is more secure.

**Comment by Shirkanesi** [comment]
Implemented in [3ae3d15ab68bf3232207b58a6673a73211c47988](https://github.com/ypsilondev/Quizzy-Backend/commit/3ae3d15ab68bf3232207b58a6673a73211c47988#diff-b0aa4d03ce3397c084b070b4b1a56191b15f73aa895f8361df5e6955fb9bbd7f)
